"""Generate notebooks/kaggle_phase2_full.ipynb — Round 6 + Cross-dataset + Phase 2 training.

Single Kaggle notebook that completes everything in `## 9 What's next` of the original
Phase 2 notebook:

  Section 1 (setup)            : clone, install negspacy + transformers + accelerate
  Section 2 (Round 6)          : negspacy-backed negation validator; re-run RadGenome held-out
  Section 3 (Cross-dataset)    : both transfer directions (TB↔RG)
  Section 4 (Phase 2 training) : 3D encoder + BART decoder, 5 epochs on 100 paired samples
  Section 5 (Generator x Val)  : generate reports on held-out subjects, run NeuroVal-3D on them
  Section 6 (Figures)          : per-epoch loss curves + final AUROC bar

Expected wall-clock on Kaggle T4 (×2): ~75–90 minutes.
"""
from __future__ import annotations

import json
from pathlib import Path

NB_PATH = Path("notebooks/kaggle_phase2_full.ipynb")


def md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(keepends=True)}


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


CELLS = [
    md(
        "# NeuroVal-3D — Phase 2 (full): Round 6, Cross-dataset, Encoder+Decoder Training\n"
        "\n"
        "Closes everything in the original Phase 2 notebook's *What's next*:\n"
        "\n"
        "1. **Round 6 — negspaCy negation validator.** Replace the regex-based negation specialist with a real medical-NLP negation tagger and re-evaluate. Lift the weakest axis (RadGenome negation 0.633) toward 0.85+.\n"
        "2. **Cross-dataset transfer** — both directions (TextBraTS ↔ RadGenome) reproduced on GPU with the upgraded validator.\n"
        "3. **Phase 2 — image-conditioned BART training.** A small 3D CNN encoder + projector + BART-base decoder, trained end-to-end on 100 BraTS-2020 volumes paired with their TextBraTS reports. Real per-epoch train/test loss curves. Generated reports validated by NeuroVal-3D — closes the generator-validator loop.\n"
        "\n"
        "Expected wall-clock on Kaggle T4 ×2: **~75–90 minutes**.\n"
    ),
    md(
        "## 0 · Prereqs (same as Phase 1 notebook)\n"
        "\n"
        "1. Settings → **Internet ON, Accelerator GPU T4 ×2**\n"
        "2. Add Data → search `brats20-dataset-training-validation` (user `awsaf49`) → Add\n"
    ),
    md(
        "## 1 · Setup — clone, install, sanity check\n"
    ),
    code(
        "GITHUB_URL = \"https://github.com/vicky-16032005/neuroval3d.git\"\n"
        "PROJECT_DIR = \"/kaggle/working/neuroval3d\"\n"
        "\n"
        "import os, subprocess, sys\n"
        "if not os.path.isdir(PROJECT_DIR):\n"
        "    subprocess.run([\"git\", \"clone\", GITHUB_URL, PROJECT_DIR], check=True)\n"
        "else:\n"
        "    subprocess.run([\"git\", \"-C\", PROJECT_DIR, \"pull\"], check=True)\n"
        "os.chdir(PROJECT_DIR)\n"
        "\n"
        "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"--upgrade\", \"pip\"], check=True)\n"
        "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\",\n"
        "                \"monai>=1.3\", \"nibabel>=5.2\", \"SimpleITK>=2.3\", \"python-dotenv\",\n"
        "                \"accelerate\", \"sentencepiece\", \"sacrebleu\", \"rouge-score\",\n"
        "                \"spacy>=3.7\", \"negspacy>=1.0.4\"], check=True)\n"
        "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"-e\", \".[data,eval]\"], check=True)\n"
        "subprocess.run([sys.executable, \"-m\", \"spacy\", \"download\", \"en_core_web_sm\"], check=True)\n"
        "print(\"setup ok\")\n"
    ),
    code(
        "import sys, importlib, torch\n"
        "for m in list(sys.modules):\n"
        "    if m == \"neuroval3d\" or m.startswith(\"neuroval3d.\"):\n"
        "        del sys.modules[m]\n"
        "_PROJECT_SRC = \"/kaggle/working/neuroval3d/src\"\n"
        "if _PROJECT_SRC not in sys.path:\n"
        "    sys.path.insert(0, _PROJECT_SRC)\n"
        "\n"
        "import neuroval3d\n"
        "print(f\"neuroval3d v{neuroval3d.__version__} from {neuroval3d.__file__}\")\n"
        "print(f\"torch {torch.__version__}, cuda {torch.cuda.is_available()}, device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'cpu'}\")\n"
        "\n"
        "import subprocess as _sp, sys as _sys\n"
        "_sp.run([_sys.executable, \"scripts/download_textbrats_reports.py\"], check=True)\n"
        "_sp.run([_sys.executable, \"scripts/download_radgenome_reports.py\"], check=True)\n"
    ),
    md(
        "## 2 · Round 6 — negspaCy negation validator\n"
        "\n"
        "Replace the regex-based `NegationValidator` with a NegEx-trained spaCy pipeline.\n"
        "Defines a drop-in `NegSpacyValidator` and monkey-patches it into the benchmark loop.\n"
    ),
    code(
        "import spacy\n"
        "from negspacy.negation import Negex\n"
        "\n"
        "_NLP = spacy.load(\"en_core_web_sm\")\n"
        "if \"negex\" not in _NLP.pipe_names:\n"
        "    _NLP.add_pipe(\"negex\", config={\"chunk_prefix\": [\"no\", \"without\", \"absent\", \"denies\", \"negative for\"]})\n"
        "\n"
        "CLINICAL_TERMS = (\n"
        "    \"edema\", \"oedema\", \"hemorrhage\", \"haemorrhage\", \"enhancement\",\n"
        "    \"restricted diffusion\", \"mass effect\", \"midline shift\", \"hydrocephalus\",\n"
        "    \"calcification\", \"cyst\", \"necrosis\", \"satellite\", \"infiltration\",\n"
        "    \"mass\", \"lesion\", \"nodule\", \"tumor\", \"tumour\", \"abnormality\", \"lesions\",\n"
        ")\n"
        "\n"
        "import re\n"
        "_TERM_PATS = {t: re.compile(rf\"\\b{re.escape(t)}\\b\", re.IGNORECASE) for t in CLINICAL_TERMS}\n"
        "\n"
        "class NegSpacyValidator:\n"
        "    \"\"\"NegEx-backed negation polarity validator. Returns set Jaccard over (term, polarity) tuples.\"\"\"\n"
        "    def extract(self, text: str) -> set[tuple[str, bool]]:\n"
        "        doc = _NLP(text)\n"
        "        # Use entity-level negation when negspaCy detects entities; otherwise fall back to pattern + negation rule\n"
        "        out: set[tuple[str, bool]] = set()\n"
        "        ent_text_to_neg: dict[str, bool] = {}\n"
        "        for ent in doc.ents:\n"
        "            ent_text_to_neg[ent.text.lower()] = bool(getattr(ent._, 'negex', False))\n"
        "        for term, pat in _TERM_PATS.items():\n"
        "            for m in pat.finditer(text.lower()):\n"
        "                # Look for an enclosing entity that has a negex flag\n"
        "                negated = False\n"
        "                for ent_text, neg in ent_text_to_neg.items():\n"
        "                    if term in ent_text:\n"
        "                        negated = neg; break\n"
        "                # Fallback: clause-aware NegEx-style scan over the preceding clause\n"
        "                if not negated:\n"
        "                    before = text.lower()[: m.start()]\n"
        "                    last_break = max(before.rfind(\".\"), before.rfind(\";\"), before.rfind(\",\"))\n"
        "                    for conj in (\" but \", \" and \", \" however \"):\n"
        "                        idx = before.rfind(conj)\n"
        "                        if idx > last_break:\n"
        "                            last_break = idx + len(conj) - 1\n"
        "                    clause = before[last_break + 1 :] if last_break >= 0 else before\n"
        "                    tokens = re.findall(r\"[\\w\\-]+\", clause)[-6:]\n"
        "                    if any(t in {\"no\", \"without\", \"absent\", \"not\", \"denies\", \"negative\", \"free\"} for t in tokens):\n"
        "                        negated = True\n"
        "                out.add((term, negated))\n"
        "        return out\n"
        "\n"
        "    def score(self, generated: str, reference: str) -> float:\n"
        "        gen, ref = self.extract(generated), self.extract(reference)\n"
        "        if not gen and not ref: return 1.0\n"
        "        if not gen or not ref: return 0.0\n"
        "        return len(gen & ref) / len(gen | ref)\n"
        "\n"
        "# Sanity check: clean ↔ flipped report\n"
        "v = NegSpacyValidator()\n"
        "ref = \"There is marked oedema. No haemorrhage.\"\n"
        "flipped = \"There is no oedema. Marked haemorrhage is present.\"\n"
        "print(f\"clean self-score:  {v.score(ref, ref):.3f}\")\n"
        "print(f\"flipped score:     {v.score(ref, flipped):.3f}\")\n"
    ),
    code(
        "# Monkey-patch NegSpacyValidator into the benchmark by replacing NegationValidator's score method.\n"
        "from neuroval3d.validators import negation as _neg_mod\n"
        "_orig = _neg_mod.NegationValidator.score\n"
        "_negspacy = NegSpacyValidator()\n"
        "_neg_mod.NegationValidator.score = lambda self, g, r, _v=_negspacy: _v.score(g, r)\n"
        "_neg_mod.NegationValidator.extract = lambda self, t, _v=_negspacy: _v.extract(t)\n"
        "print(\"NegationValidator now backed by negspaCy\")\n"
    ),
    md(
        "## 3 · Cross-dataset transfer (with the upgraded negation axis)\n"
        "\n"
        "Both directions: TextBraTS → RadGenome and reverse.\n"
    ),
    code(
        "from neuroval3d.data import textbrats_reports_only, radgenome_reports_only\n"
        "from neuroval3d.evaluation.benchmark import run_cross_dataset_benchmark\n"
        "\n"
        "tb = textbrats_reports_only()\n"
        "rg = radgenome_reports_only()\n"
        "print(f\"TextBraTS: {len(tb)}, RadGenome: {len(rg)}\")\n"
        "\n"
        "print(\"\\n=== Cross 1/2: TextBraTS -> RadGenome ===\")\n"
        "r_tb_rg = run_cross_dataset_benchmark(\n"
        "    train_reports=tb, test_reports=rg,\n"
        "    train_label=\"textbrats\", test_label=\"radgenome\",\n"
        ")\n"
        "print(r_tb_rg.summary_table())\n"
    ),
    code(
        "print(\"\\n=== Cross 2/2: RadGenome -> TextBraTS ===\")\n"
        "r_rg_tb = run_cross_dataset_benchmark(\n"
        "    train_reports=rg, test_reports=tb,\n"
        "    train_label=\"radgenome\", test_label=\"textbrats\",\n"
        ")\n"
        "print(r_rg_tb.summary_table())\n"
    ),
    md(
        "## 4 · Phase 2 — Image-conditioned BART training\n"
        "\n"
        "End-to-end pipeline:\n"
        "\n"
        "1. Pair 100 BraTS-2020 volumes with their TextBraTS reports.\n"
        "2. Stage 1 preprocessing (already in `neuroval3d.data.preprocessing`).\n"
        "3. Small 3D CNN encoder → 32 image tokens.\n"
        "4. BART-base decoder, with image tokens as `encoder_outputs` for cross-attention.\n"
        "5. Train 5 epochs on 80 paired samples; hold out 20 for evaluation.\n"
        "6. Track per-epoch train/test cross-entropy loss.\n"
    ),
    code(
        "import os\n"
        "import re\n"
        "from pathlib import Path\n"
        "import numpy as np\n"
        "import torch\n"
        "import torch.nn as nn\n"
        "import torch.nn.functional as F\n"
        "from torch.utils.data import Dataset, DataLoader\n"
        "from neuroval3d.data import Stage1Preprocessor, PreprocessingConfig\n"
        "\n"
        "DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n"
        "TARGET_SHAPE = (64, 64, 64)\n"
        "N_PAIRED = 100\n"
        "TRAIN_FRAC = 0.8\n"
        "\n"
        "# Find BraTS root (same logic as Phase 1 notebook)\n"
        "def find_brats_root() -> Path | None:\n"
        "    base = Path(\"/kaggle/input\")\n"
        "    for p in base.rglob(\"MICCAI_BraTS2020_TrainingData\"):\n"
        "        if p.is_dir(): return p\n"
        "    return None\n"
        "\n"
        "BRATS_ROOT = find_brats_root()\n"
        "if BRATS_ROOT is None:\n"
        "    raise SystemExit(\"BraTS dataset not attached. Right rail: Add Data -> awsaf49/brats20-dataset-training-validation\")\n"
        "print(\"BraTS root:\", BRATS_ROOT)\n"
        "\n"
        "# List paired (subject, report_path) for the first N_PAIRED subjects that have both volume + report\n"
        "REPORTS_DIR = Path(\"data/raw/TextBraTS/reports\")\n"
        "available_reports = {p.stem: p for p in REPORTS_DIR.glob(\"*.txt\")}\n"
        "pairs: list[tuple[str, Path, Path]] = []\n"
        "for subj_dir in sorted(BRATS_ROOT.glob(\"BraTS20_Training_*\")):\n"
        "    sid = subj_dir.name\n"
        "    if sid in available_reports:\n"
        "        pairs.append((sid, subj_dir, available_reports[sid]))\n"
        "    if len(pairs) >= N_PAIRED:\n"
        "        break\n"
        "print(f\"Paired subjects: {len(pairs)} (taking first {N_PAIRED})\")\n"
    ),
    code(
        "# Quick preview: first paired report\n"
        "sid, sdir, rpath = pairs[0]\n"
        "print(f\"Subject: {sid}\")\n"
        "print(f\"Report:  {rpath.read_text(encoding='utf-8')[:300]}...\")\n"
    ),
    code(
        "# Custom preprocessing dataset — caches the preprocessed volume tensors in memory.\n"
        "# 100 volumes × 4 modalities × 64^3 × float32 = ~100 MB → fine on Kaggle.\n"
        "from tqdm.auto import tqdm\n"
        "\n"
        "_pre = Stage1Preprocessor(PreprocessingConfig(\n"
        "    target_shape=TARGET_SHAPE,\n"
        "    bias_correct=False,  # skip N4 to save time on 100 volumes; quality is fine for demo\n"
        "    normalize=\"zscore\",\n"
        "))\n"
        "\n"
        "preprocessed: list[tuple[str, np.ndarray, str]] = []\n"
        "for sid, sdir, rpath in tqdm(pairs, desc=\"preprocessing volumes\"):\n"
        "    paths = {\n"
        "        m: str(sdir / f\"{sid}_{m_low}.nii\")\n"
        "        for m, m_low in [(\"T1\", \"t1\"), (\"T1ce\", \"t1ce\"), (\"T2\", \"t2\"), (\"FLAIR\", \"flair\")]\n"
        "    }\n"
        "    out = _pre.run(paths)\n"
        "    preprocessed.append((sid, out.volume.astype(np.float32), rpath.read_text(encoding=\"utf-8\").strip()))\n"
        "print(f\"Preprocessed: {len(preprocessed)} volumes  shape={preprocessed[0][1].shape}\")\n"
    ),
    code(
        "# Tokenize reports with the BART tokenizer\n"
        "from transformers import BartTokenizer\n"
        "TOKENIZER = BartTokenizer.from_pretrained(\"facebook/bart-base\")\n"
        "MAX_TGT_LEN = 200\n"
        "\n"
        "def encode_report(text: str) -> dict:\n"
        "    enc = TOKENIZER(text, max_length=MAX_TGT_LEN, padding=\"max_length\",\n"
        "                    truncation=True, return_tensors=\"pt\")\n"
        "    labels = enc.input_ids[0].clone()\n"
        "    labels[labels == TOKENIZER.pad_token_id] = -100  # ignore padding in loss\n"
        "    return {\"input_ids\": enc.input_ids[0], \"labels\": labels}\n"
        "\n"
        "_first = encode_report(preprocessed[0][2])\n"
        "print(\"input_ids:\", _first['input_ids'].shape, \"labels:\", _first['labels'].shape)\n"
    ),
    code(
        "class BratsReportDataset(Dataset):\n"
        "    def __init__(self, items):\n"
        "        self.items = items\n"
        "        self.cached_tokens = [encode_report(r) for _, _, r in items]\n"
        "    def __len__(self): return len(self.items)\n"
        "    def __getitem__(self, i):\n"
        "        sid, vol, _ = self.items[i]\n"
        "        toks = self.cached_tokens[i]\n"
        "        return {\n"
        "            \"volume\": torch.from_numpy(vol),  # [4, D, H, W]\n"
        "            \"labels\": toks[\"labels\"],\n"
        "        }\n"
        "\n"
        "n_train = int(len(preprocessed) * TRAIN_FRAC)\n"
        "train_items = preprocessed[:n_train]\n"
        "test_items = preprocessed[n_train:]\n"
        "train_ds = BratsReportDataset(train_items)\n"
        "test_ds = BratsReportDataset(test_items)\n"
        "print(f\"train: {len(train_ds)}, test: {len(test_ds)}\")\n"
    ),
    code(
        "# Architecture:\n"
        "#   3D CNN encoder (3 conv blocks + global pool) -> projector -> 32 tokens x 768 dim\n"
        "#   BART-base decoder consumes those as encoder_outputs (cross-attention K/V)\n"
        "from transformers import BartForConditionalGeneration\n"
        "\n"
        "BART = BartForConditionalGeneration.from_pretrained(\"facebook/bart-base\").to(DEVICE)\n"
        "EMB_DIM = BART.config.d_model  # 768 for bart-base\n"
        "N_IMG_TOKENS = 32\n"
        "\n"
        "class Encoder3D(nn.Module):\n"
        "    def __init__(self, in_ch: int = 4, hidden: int = 64):\n"
        "        super().__init__()\n"
        "        self.conv = nn.Sequential(\n"
        "            nn.Conv3d(in_ch, hidden, 3, padding=1, stride=2), nn.GroupNorm(8, hidden), nn.GELU(),\n"
        "            nn.Conv3d(hidden, hidden * 2, 3, padding=1, stride=2), nn.GroupNorm(8, hidden * 2), nn.GELU(),\n"
        "            nn.Conv3d(hidden * 2, hidden * 4, 3, padding=1, stride=2), nn.GroupNorm(8, hidden * 4), nn.GELU(),\n"
        "        )\n"
        "        self.feat_dim = hidden * 4\n"
        "    def forward(self, x):\n"
        "        z = self.conv(x)            # [B, C, d, h, w]  d/h/w = D/8\n"
        "        B, C, D, H, W = z.shape\n"
        "        z = z.view(B, C, -1).permute(0, 2, 1)   # [B, T, C] where T = d*h*w\n"
        "        return z\n"
        "\n"
        "class Projector(nn.Module):\n"
        "    def __init__(self, in_dim: int, out_dim: int = EMB_DIM, n_tokens: int = N_IMG_TOKENS):\n"
        "        super().__init__()\n"
        "        self.n_tokens = n_tokens\n"
        "        self.linear = nn.Linear(in_dim, out_dim)\n"
        "        self.query = nn.Parameter(torch.randn(n_tokens, out_dim) * 0.02)\n"
        "        self.attn = nn.MultiheadAttention(out_dim, num_heads=8, batch_first=True)\n"
        "    def forward(self, z):\n"
        "        z = self.linear(z)               # [B, T, D]\n"
        "        B = z.size(0)\n"
        "        q = self.query.unsqueeze(0).expand(B, -1, -1)\n"
        "        out, _ = self.attn(q, z, z)      # [B, n_tokens, D]\n"
        "        return out\n"
        "\n"
        "class Brain3DReportGen(nn.Module):\n"
        "    def __init__(self):\n"
        "        super().__init__()\n"
        "        self.encoder = Encoder3D()\n"
        "        self.projector = Projector(self.encoder.feat_dim)\n"
        "        self.bart = BART\n"
        "    def forward(self, volume, labels=None):\n"
        "        z = self.encoder(volume)\n"
        "        img_tokens = self.projector(z)             # [B, n_tokens, D]\n"
        "        # BartForConditionalGeneration.forward expects encoder_outputs as a BaseModelOutput-like obj\n"
        "        from transformers.modeling_outputs import BaseModelOutput\n"
        "        enc_out = BaseModelOutput(last_hidden_state=img_tokens)\n"
        "        return self.bart(\n"
        "            encoder_outputs=enc_out,\n"
        "            attention_mask=torch.ones(img_tokens.shape[:2], device=img_tokens.device),\n"
        "            labels=labels,\n"
        "        )\n"
        "    @torch.no_grad()\n"
        "    def generate(self, volume, max_len: int = MAX_TGT_LEN, num_beams: int = 4):\n"
        "        from transformers.modeling_outputs import BaseModelOutput\n"
        "        z = self.encoder(volume)\n"
        "        img_tokens = self.projector(z)\n"
        "        enc_out = BaseModelOutput(last_hidden_state=img_tokens)\n"
        "        return self.bart.generate(\n"
        "            encoder_outputs=enc_out,\n"
        "            attention_mask=torch.ones(img_tokens.shape[:2], device=img_tokens.device),\n"
        "            max_length=max_len, num_beams=num_beams, no_repeat_ngram_size=3,\n"
        "        )\n"
        "\n"
        "model = Brain3DReportGen().to(DEVICE)\n"
        "n_params = sum(p.numel() for p in model.parameters())\n"
        "print(f\"Model parameters: {n_params/1e6:.1f}M\")\n"
    ),
    code(
        "# Training loop with per-epoch train/test loss tracking\n"
        "import time\n"
        "\n"
        "BATCH_SIZE = 2\n"
        "N_EPOCHS = 5\n"
        "LR = 1e-4\n"
        "\n"
        "train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)\n"
        "test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=0)\n"
        "\n"
        "optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=0.01)\n"
        "\n"
        "history = {\"train_loss\": [], \"test_loss\": []}\n"
        "for epoch in range(1, N_EPOCHS + 1):\n"
        "    t0 = time.time()\n"
        "    model.train()\n"
        "    train_losses = []\n"
        "    for batch in tqdm(train_loader, desc=f\"epoch {epoch} train\"):\n"
        "        vol = batch[\"volume\"].to(DEVICE)\n"
        "        labels = batch[\"labels\"].to(DEVICE)\n"
        "        out = model(vol, labels=labels)\n"
        "        out.loss.backward()\n"
        "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n"
        "        optimizer.step(); optimizer.zero_grad()\n"
        "        train_losses.append(float(out.loss.item()))\n"
        "    model.eval()\n"
        "    test_losses = []\n"
        "    with torch.no_grad():\n"
        "        for batch in test_loader:\n"
        "            vol = batch[\"volume\"].to(DEVICE)\n"
        "            labels = batch[\"labels\"].to(DEVICE)\n"
        "            out = model(vol, labels=labels)\n"
        "            test_losses.append(float(out.loss.item()))\n"
        "    train_l = float(np.mean(train_losses))\n"
        "    test_l  = float(np.mean(test_losses))\n"
        "    history[\"train_loss\"].append(train_l)\n"
        "    history[\"test_loss\"].append(test_l)\n"
        "    dt = time.time() - t0\n"
        "    print(f\"  epoch {epoch}: train_loss={train_l:.4f}  test_loss={test_l:.4f}  ({dt:.1f}s)\")\n"
        "\n"
        "torch.save(model.state_dict(), \"/kaggle/working/brain3d_reportgen.pt\")\n"
        "print(\"\\nSaved checkpoint to /kaggle/working/brain3d_reportgen.pt\")\n"
    ),
    md(
        "## 5 · Generator × Validator — close the loop\n"
        "\n"
        "Use the trained model to generate reports for held-out test subjects, then run NeuroVal-3D on (generated, reference) pairs. The validator should give high scores when the generator does well, low scores when it hallucinates.\n"
    ),
    code(
        "model.eval()\n"
        "generated_reports: list[str] = []\n"
        "reference_reports: list[str] = []\n"
        "with torch.no_grad():\n"
        "    for sid, vol, ref in tqdm(test_items, desc=\"generating\"):\n"
        "        v = torch.from_numpy(vol).unsqueeze(0).to(DEVICE)\n"
        "        out_ids = model.generate(v, max_len=MAX_TGT_LEN, num_beams=4)\n"
        "        gen = TOKENIZER.decode(out_ids[0], skip_special_tokens=True)\n"
        "        generated_reports.append(gen)\n"
        "        reference_reports.append(ref)\n"
        "        if len(generated_reports) <= 3:\n"
        "            print(f\"\\n--- {sid} ---\\nREF: {ref[:160]}...\\nGEN: {gen[:160]}...\")\n"
    ),
    code(
        "# Run NeuroVal-3D on the (generated, reference) pairs.\n"
        "from neuroval3d.validators import (\n"
        "    SemanticValidator, LexicalValidator, StructuralValidator,\n"
        "    NumericValidator, ModalityValidator, NegationValidator, LesionTypeValidator,\n"
        "    FusionValidator, RaTEScoreLite,\n"
        ")\n"
        "\n"
        "sem = SemanticValidator()\n"
        "lex = LexicalValidator().fit(generated_reports + reference_reports)\n"
        "struct = StructuralValidator()\n"
        "num = NumericValidator(); modv = ModalityValidator()\n"
        "neg = NegationValidator()  # already monkey-patched to negspaCy\n"
        "lt = LesionTypeValidator()\n"
        "rs = RaTEScoreLite()\n"
        "\n"
        "axis_scores: list[dict[str, float]] = []\n"
        "for g, r in tqdm(list(zip(generated_reports, reference_reports)), desc=\"validating\"):\n"
        "    axis_scores.append({\n"
        "        \"semantic\": sem.score(g, r), \"lexical\": lex.score(g, r),\n"
        "        \"structural\": struct.score(g, r), \"numeric\": num.score(g, r),\n"
        "        \"modality\": modv.score(g, r), \"negation\": neg.score(g, r),\n"
        "        \"lesion_type\": lt.score(g, r), \"ratescore_lite\": rs.score(g, r),\n"
        "    })\n"
        "\n"
        "import pandas as pd\n"
        "axes_df = pd.DataFrame(axis_scores)\n"
        "print(axes_df.describe().T[[\"mean\", \"std\", \"min\", \"max\"]].round(3))\n"
    ),
    md(
        "## 6 · Figures — loss curves + final validation chart\n"
    ),
    code(
        "import matplotlib.pyplot as plt\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(15, 5))\n"
        "\n"
        "# Loss curves\n"
        "epochs = list(range(1, len(history[\"train_loss\"]) + 1))\n"
        "axes[0].plot(epochs, history[\"train_loss\"], \"-o\", label=\"train\", color=\"#264653\", linewidth=2)\n"
        "axes[0].plot(epochs, history[\"test_loss\"],  \"-o\", label=\"test\",  color=\"#2a9d8f\", linewidth=2)\n"
        "axes[0].set_xlabel(\"epoch\")\n"
        "axes[0].set_ylabel(\"cross-entropy loss\")\n"
        "axes[0].set_title(\"Phase 2 — BART-base + 3D CNN encoder, training curves\")\n"
        "axes[0].legend()\n"
        "axes[0].grid(alpha=0.3)\n"
        "\n"
        "# Mean per-axis score on real generations\n"
        "axis_means = axes_df.mean()\n"
        "axes[1].bar(axis_means.index, axis_means.values, color=\"#2a9d8f\")\n"
        "axes[1].axhline(0.5, ls=\":\", color=\"gray\", alpha=0.7, label=\"random\")\n"
        "axes[1].set_xticklabels(axis_means.index, rotation=30, ha=\"right\")\n"
        "axes[1].set_ylabel(\"mean validator score (gen vs ref)\")\n"
        "axes[1].set_title(\"NeuroVal-3D scores on Phase 2 model output\")\n"
        "axes[1].set_ylim([0, 1])\n"
        "axes[1].legend()\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.savefig(\"/kaggle/working/phase2_full_summary.png\", dpi=140, bbox_inches=\"tight\")\n"
        "plt.show()\n"
    ),
    md(
        "## 7 · What lives in `/kaggle/working/` after this notebook\n"
        "\n"
        "- `brain3d_reportgen.pt` — trained Phase 2 model checkpoint (~600 MB)\n"
        "- `phase2_full_summary.png` — loss curves + final validator score chart\n"
        "- `neuroval3d/outputs/results/<run_id>/` — per-run AUROC tables for both cross-dataset transfers\n"
        "\n"
        "## What just happened (paper-ready summary)\n"
        "\n"
        "1. **Round 6:** the negation specialist now uses negspaCy. Cross-dataset numbers reproduced with the upgraded validator (Section 3 output).\n"
        "2. **Phase 2:** a small 3D CNN + BART decoder trained end-to-end on real BraTS volumes paired with TextBraTS reports. Per-epoch train and test loss are visible in the curve. The trained generator's output is then *validated by NeuroVal-3D* — closing the generator-validator loop on a single dataset.\n"
        "3. The mean per-axis scores in the second chart show how a real (under-trained) generator compares to clean references. Lower scores reveal the kinds of mistakes the generator makes; higher scores show the validator is robust to fluent paraphrases.\n"
    ),
]


def main() -> None:
    NB_PATH.parent.mkdir(parents=True, exist_ok=True)
    nb = {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
            "kaggle": {"accelerator": "gpu"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    NB_PATH.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {NB_PATH}")


if __name__ == "__main__":
    main()
